### ISSUE TITLE
peer review

### ISSUE THREAD

**Issue by Rickenn** [RayanAlim/Toronto_flooding_analysis#3]
Opening statement summary
This paper examines basement flooding and the need for sewer service in Toronto from 2005 to 2023. It also suggests how sewage services can be improved to avoid flood risk.

Strong positive points
Provide clear graph to allow the reader to recognize the importance of the drainage system.

Critical improvements needed
The number of icons is too small, indicating that the quantitative data of the study is not fully represented or that the topic does not contain too much quantitative data. The citation is only one or two, indicating that there is not enough data to support the final conclusion.

Suggestions for improvement:
Could do with a few more charts and refer to more literature.

Please consider adding/changing/removing:
1: not only line plots, can try other different plots to express data.
2: try to find another reference that can evident your result or opinion.

Evaluation:
This paper does a good job of showing some of his data, but some of it is not enough and could be strengthened in terms of data visualization.

Estimated mark:
70 out of 100.

Reason:
This essay makes good use of knowledge from the class and is a well-done assignment, but it is not complete enough as far as data analysis is concerned.

**Comment by RayanAlim** [comment]
Added:
- A different plot
- Some sources to back some of the things i said in my into
