### ISSUE TITLE
peer review - Xinze Wu

### ISSUE THREAD

**Issue by ke3w** [RayanAlim/Toronto_flooding_analysis#5]
Opening Statement Summary:
This paper focuses on analyzing basement flooding and sewage service across Toronto wards from 2005 to 2023. The process of code analysis is divided into 4 parts(simulate/download/clean/test data, ) which is well-organized. Besides, there is also a figure work which indicates the key features of the data pretty well. 

Strong Positive Points:
The code part is well-organized and readable and the code writing is efficient. Plus the code test part is also very comprehensive. The paper is well-structured which perfectly follows the requirements of the task, and the figure in the paper also makes it easier for people to understand the features of the data.

Critical Improvements Needed:
Paper: The content for part Discuss is not enough, and the Result part is missing. And it might be better to use one more figure work to express the relationship between the variables from another perspective. However, it is not a big deal since this is only the draft work.
Code: Overall is very good
README: The content of the overview can be more detailed.

Suggestions for Improvement:
Add a 'Result' part at the end of the paper, make conclusion about the process of the analysis and your personal thinking for the result.
Add content about data sources, methods of data analysis, and a brief explanation of the paper structure.

Evaluation:
According to the draft work, I would give 85-88 to the final work(including the improvements and full-text paper)

Estimated Mark:
87

Reason:
The code part is very efficient and well-organized, but if the dataset selected from Open Data Toronto is more complex, for example, involves several independent variables, the paperwork can be more professional. 
The paper part is also good but not finished yet, would be great after finishing.

**Comment by RayanAlim** [comment]
Thank you for the review! I have addressed the following:
- Made READM more detailed.
- Addedd more information about the dataset , data sources, methods of data analysis, and a brief explanation of the paper structure
